name: emoti_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  # http: ^0.13.6
  chewie: ^1.5.2
  intl: ^0.18.1
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  firebase_storage: ^12.1.3
  firebase_core: ^3.6.0
  flutter_tts: ^4.2.0
  audioplayers: ^6.1.0
  path_drawing: ^1.0.1
  video_player: ^2.8.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  http: ^1.2.0
  
  
  
  
  

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  provider: ^6.1.2
  share_plus: ^7.2.2

  # 100% Flutter 3.22 compatible
  fl_chart: ^0.66.0

  # For YouTube videos
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.1.0

  # FIXED — awesome_notifications 0.9.x supports latest Flutter + AGP 8+
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboard2.png
    - assets/images/onboard1.jpg
    - assets/images/onboard3.png
    - assets/images/emoti connect.png
    - assets/images/password.png
    - assets/images/confused.png
    - assets/images/excited.png
    - assets/images/lonely.png
    - assets/images/sad.png
    - assets/images/tired.png
    - assets/images/stressed.png
    - assets/images/support.png
    - assets/images/emotions.png
    - assets/images/daily.png
    - assets/images/copying.png
    - assets/images/consequences.png
    - assets/images/challenges.png
    - assets/images/female.png
    - assets/images/male.png
    - assets/images/meditation.png

